flower_project_api_getbyaccount:
    path:     /account/{accountId}
    defaults: { _controller: FlowerProjectBundle:Api\Project:getByAccount }

flower_project_api_getone:
    path:     /{id}
    defaults: { _controller: FlowerProjectBundle:Api\Project:getById }

flower_project_api_getall:
    path:     /
    defaults: { _controller: FlowerProjectBundle:Api\Project:getAll }
