services:
    form.type.project:
        class: Flower\ProjectBundle\Form\Type\ProjectType
        arguments: ["@security.context"]
        tags:
            - { name: form.type, alias: project_type }    
    form.type.docproject:
        class: Flower\ProjectBundle\Form\Type\DocPageType
        arguments: ["@security.context"]
        tags:
            - { name: form.type, alias: project_type }    
    flower.project:
        class: Flower\ProjectBundle\Service\ProjectService
        arguments: ['@security.context']
        calls:
          - [ setContainer,[ @service_container ] ]

          