<?php

namespace Flower\ProjectBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EstimationItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstimationItemRepository extends EntityRepository
{
}
