<?php

namespace Flower\ProjectBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EstimationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstimationRepository extends EntityRepository
{
}
