<?php

namespace Flower\ProjectBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectIterationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectIterationRepository extends EntityRepository
{
    public function findWithStats($projectId, $clientView = false)
    {
        $qb = $this->createQueryBuilder("i");
        $qb->select("i.id, i.name, i.startDate, i.dueDate, i.status, SUM(t.estimated) as estimation
        , SUM(case when ts.name = 'todo' then 1 else 0 end) as todo_count
        , SUM(case when ts.name = 'doing' then 1 else 0 end) as doing_count
        , SUM(case when ts.name = 'done' then 1 else 0 end) as done_count");
        $qb->leftJoin("i.tasks", "t");
        $qb->leftjoin("t.status", "ts");
        $qb->where("i.project = :project_id")->setParameter("project_id", $projectId);
        if ($clientView) {
            $qb->andWhere('i.clientViewable = :client_view')->setParameter('client_view', true);
        }
        $qb->groupBy("i.id")
            ->orderBy("i.startDate");
        return $qb->getQuery()->getArrayResult();
    }

    public function findSpentByProject($projectId, $clientView = false)
    {
        $qb = $this->createQueryBuilder("i");
        $qb->select("SUM(tl.hours) as spent");
        $qb->leftJoin("i.tasks", "t");
        $qb->leftJoin("t.timeLogs", "tl");
        $qb->where("i.project = :project_id")->setParameter("project_id", $projectId);
        $qb->where("i.project = :project_id")->setParameter("project_id", $projectId);
        if ($clientView) {
            $qb->andWhere('i.clientViewable = :client_view')->setParameter('client_view', true);
        }
        $qb->groupBy("i.id")
            ->orderBy("i.startDate");
        return $qb->getQuery()->getArrayResult();
    }

    public function findOneWithStats($projectIteration)
    {
        $qb = $this->createQueryBuilder("i");
        $qb->select("i.id, i.name, i.startDate, i.dueDate, i.status, SUM(t.estimated) as estimation
        , SUM(case when ts.name = 'todo' then 1 else 0 end) as todo_count
        , SUM(case when ts.name = 'doing' then 1 else 0 end) as doing_count
        , SUM(case when ts.name = 'done' then 1 else 0 end) as done_count");
        $qb->leftJoin("i.tasks", "t");
        $qb->leftjoin("t.status", "ts");
        $qb->where("i.id = :projectIteration")->setParameter("projectIteration", $projectIteration);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
